server:
  port: 9100
  context-path: /rvs-api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rvs?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active: test
frontend: http://localhost:3000